baseurl: ""
languageCode: en-US
title: "Jaren's Github Pages Site"
description: "A website built to display my work through the SMU Data Science Program"
theme: jekyll-theme-cayman
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/jshead
    - name: Youtube
      url: https://youtu.be/QOnWDLSzs-w
    - name: R Shiny
      url: https://jshead.shinyapps.io/CaseStudy2App/
